### ISSUE TITLE
No such module 'TarantoolConnector'

### ISSUE THREAD

**Issue by yurytom** [tris-foundation/tarantool#27]
Hi there,

I have added the package as pointed in the documentation 
.package(url: "https://github.com/tris-foundation/tarantool.git", .branch("master"))

My project fails during compilation with following error
No such module 'TarantoolConnector'

Xcode 9.4.1
Swift 4.1

I assume .branch is not supported anymore. 
Could you guide how to fix that? 

Thanks,
Yury

**Comment by tonyfreeman** [comment]
Hi @yurytom, 
for Swift 4.1 you should use .branch("4.1"), "master" branch uses the next version of Swift (4.2-dev).

**Comment by yurytom** [comment]
Thanks @tonyfreeman for a prompt reply.

It's still not working. Same error message. Below is my Package.swift file.

import PackageDescription
let package = Package(
	name: "server",
	targets: [],
	dependencies: [
        .Package(url: "https://github.com/tris-foundation/tarantool.git", .branch("4.1"),
	.Package(url: "https://github.com/PerfectlySoft/Perfect-HTTPServer.git", versions: Version(3,0,0)..<Version(3,9223372036854775807,9223372036854775807)),
	.Package(url: "https://github.com/PerfectlySoft/Perfect-RequestLogger.git", versions: Version(3,0,0)..<Version(3,9223372036854775807,9223372036854775807)),
	.Package(url: "https://github.com/PerfectlySoft/PerfectLib.git", versions: Version(3,0,0)..<Version(3,9223372036854775807,9223372036854775807)),
	]
)


Is .branch right syntax? I couldn't find it in the Dependency class.

` public class Dependency {

        public let versionRange: Range<PackageDescription.Version>

        public let url: String

        public class func Package(url: String, versions: Range<PackageDescription.Version>) -> PackageDescription.Package.Dependency

        public class func Package(url: String, versions: ClosedRange<PackageDescription.Version>) -> PackageDescription.Package.Dependency

        public class func Package(url: String, majorVersion: Int) -> PackageDescription.Package.Dependency

        public class func Package(url: String, majorVersion: Int, minor: Int) -> PackageDescription.Package.Dependency

        public class func Package(url: String, _ version: PackageDescription.Version) -> PackageDescription.Package.Dependency
    }`

**Comment by tonyfreeman** [comment]
@yurytom that's because you're using obsolete (v3) version of Package.swift, it does work in Swift 4 for compatibility issues, but doesn't support new features. Here is an example of v4 https://github.com/tris-foundation/examples/tree/master/tarantool/connector/Package.swift.

**Comment by yurytom** [comment]
sorry for a silly question, but how to switch to PM v4 in Xcode?

**Comment by tonyfreeman** [comment]
It's not possible, the Package.swift is not a part of Xcode's project, you should rewrite your Package.swift manually then run `swift package generate-xcodeproj" to regenerate(update) your project. You can join http://t.me/trisfoundation, https://t.me/swiftlangru or contact me directly if you have any question about the project or swift itself.

**Comment by yurytom** [comment]
Thank you, Sir

**Comment by yurytom** [comment]
for future generations 

```
// swift-tools-version:4.0

import PackageDescription

let package = Package(
    name: "server",
    dependencies: [
        .package(url: "https://github.com/PerfectlySoft/Perfect-HTTPServer.git", from: "3.0.0"),
        .package(url: "https://github.com/PerfectlySoft/PerfectLib.git", from: "3.0.0"),
        .package(url: "https://github.com/tris-foundation/tarantool.git", .branch("4.1"))
    ],
    targets: [
        .target(name: "server", dependencies: ["PerfectHTTPServer", "PerfectLib", "TarantoolConnector"])
    ]
)
```

swift package generate-xcodeproj
swift package reset
swift package update
